# Generated by Django 2.2.2 on 2019-06-17 22:09

from django.db import migrations, models
import presentation_manager.validators


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presentations",
                validators=[presentation_manager.validators.validate_presentation_file],
            ),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="duration",
            field=models.FloatField(
                help_text="Duration of a presentation of this type [min.]."
            ),
        ),
    ]
