# Generated by Django 2.2.2 on 2019-07-09 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0003_auto_20190618_2006")]

    operations = [
        migrations.RemoveField(model_name="presentation", name="id"),
        migrations.AddField(
            model_name="presentation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="duration",
            field=models.DurationField(
                help_text="Duration of a presentation of this type."
            ),
        ),
    ]
