# Generated by Django 2.2.2 on 2019-07-14 16:29

from django.db import migrations, models
import presentation_manager.formats.formats


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0004_auto_20190709_2024")]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presentations",
                validators=[
                    presentation_manager.formats.formats.validate_format
                ],
            ),
        )
    ]
