# Generated by Django 2.2.2 on 2019-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0006_presentation_format")]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("49235f37aa173b3d48eb6d856229e4c4", "PDF")],
                max_length=32,
                null=True,
            ),
        ),
    ]
