# Generated by Django 2.2.2 on 2019-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0007_auto_20190714_1852")]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="order",
            field=models.IntegerField(default=-1),
        )
    ]
