# Generated by Django 2.2.2 on 2019-07-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("presentation_manager", "0008_presentation_order")]

    operations = [
        migrations.AlterModelOptions(
            name="presentation", options={"ordering": ("order",)}
        )
    ]
